@echo off
echo Adding GIT_HOOKS.md to staging area...
git add GIT_HOOKS.md
echo Committing changes...
git commit -m "restore: Add back GIT_HOOKS.md documentation"
echo Pushing to remote repository...
git push
echo Done! 