name: Visual Regression Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  visual-regression:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook

      - name: Percy Visual Testing
        uses: percy/storybook-action@v1
        with:
          storybook_build_dir: 'storybook-static'
          storybook_config_dir: '.storybook'
          storybook_static_dir: 'public'
          storybook_port: 6006
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
